### ISSUE TITLE
Problem with version 0.0.3

### ISSUE THREAD

**Issue by Amoyaz** [rajangdavis/osc_node#1]
When I update to the version of osc_node 0.03 recibe this error:
________________________________________________________________________
[ec2-user@ip-172-31-16-32 RN_PureCloud]$ node rn_test.js
module.js:557
    throw err;
    ^

Error: Cannot find module 'osc_node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/RN_PureCloud/rn_test.js:1:79)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
________________________________________________________________________

But the module 'osc_node' is declared in the "rn_test.js" file, when rollback the module to the version 0.01, the app work correctly.

**Comment by rajangdavis** [comment]
Hi, can you show me the contents of your package.json file? I set up a quick node app and it worked... This is what I did (in the command line):
```
$ mkdir node_test
$ cd node_test
$ touch test.js
$ npm init
$ npm install osc_node
```
In the test.js, I have the following code:
```
const OSCNode = require('osc_node');
const env = process.env;

var rn_client = OSCNode.Client({
	username: env['OSC_ADMIN'],
	password: env['OSC_PASSWORD'],
	interface: env['OSC_SITE'],
	// Optional Configuration Settings
	demo_site: true,
});

var options = {
	client: rn_client,
	id: 176
}

OSCNode.AnalyticsReportResults.run(options,function(err,data){
	console.log(data);

	data.map((res)=>{
		console.log(`Columns: ${Object.keys(res).join(", ")}`);
		console.log(`Values: ${Object.values(res).join(", ")}`);
	})
});
```

**Comment by rajangdavis** [comment]
Also, I downloaded your Test_PureCloudAMoya app...

You need to delete the node_modules folder and the package-lock.json file; you probably shouldn't upload these into your git repo. 

Change the version of osc_node to 0.0.3 in your package.json and type "npm install".

Also, for the love of God, please don't put your credentials in plain text in your 'rn_test.js'. Please use environmental variables...
